all:
	N=1024 CL_PLAT=0 ./make.sh
	N=2048 CL_PLAT=0 ./make.sh
	N=4096 CL_PLAT=0 ./make.sh
	
	N=1024 CL_PLAT=1 ./make.sh
	N=2048 CL_PLAT=1 ./make.sh
	N=4096 CL_PLAT=1 ./make.sh

clean:
	rm matrix_mul_ocl_N*
	